create table if not exists "trainCategories"
(
    "categoryID"   int generated by default as identity primary key,
    "categoryName" varchar(50) not null unique
);

create table if not exists stations
(
    id   int generated by default as identity primary key,
    name varchar(100) not null
);

create table if not exists trains
(
    id              int generated by default as identity primary key,
    "trainNumber"   varchar(20) not null,
    "categoryID"    int         not null references "trainCategories" ("categoryID"),
    "quantityWagon" int         not null default 0
);

create table if not exists "wagonType"
(
    id       int generated by default as identity primary key,
    type     varchar(100) not null,
    capacity int          not null
);

create table if not exists wagons
(
    id            int generated by default as identity primary key,
    "trainID"     int references trains (id),
    "wagonTypeID" int not null references "wagonType" (id)
);

create table if not exists routes
(
    id                   int generated by default as identity primary key,
    "departureStationID" int not null references stations (id),
    "arrivalStationID"   int not null references stations (id)
);

create table if not exists schedule
(
    "id"      int generated by default as identity primary key,
    "routeID" int not null references routes (id),
    "trainID" int not null references trains (id)
);

create table if not exists "timeSchedule"
(
    "scheduleID"         int references schedule (id),
    "stationID"          int references stations (id),
    "plannedArrivalTime" timestamp with time zone default null,
    "realArrivalTime"    timestamp with time zone default null,
    "stopDuration"       interval not null,
    primary key ("scheduleID", "stationID")
);

create table if not exists "routeStations"
(
    "routeID"   int not null references routes (id),
    "stationID" int not null references stations (id),
    "stopOrder" int not null,
    "distance"  int not null, -- (расстояние от предыдущей станции маршрута до текущей)
    primary key ("routeID", "stationID")
);

create table if not exists passengers
(
    id             int generated by default as identity primary key,
    "passportData" varchar(50) not null unique,
    firstname      varchar(30) not null,
    surname        varchar(30) not null,
    patronymic     varchar(30) default null
);

create table if not exists "passengersTrips"
(
    id                   int generated by default as identity primary key,
    "scheduleID"         int not null references schedule (id),
    "passengerID"        int not null references passengers (id),
    "departureStationID" int not null references stations (id),
    "arrivalStationID"   int not null references stations (id),
    "wagonID"            int not null references wagons (id),
    "placeNumber"        int not null check ("placeNumber" > 0)
);

create table if not exists "brigades"
(
    id              int generated by default as identity primary key,
    "trainID"       int references trains (id),
    "headStationID" int references stations (id)
);

create table if not exists employees
(
    id          int generated by default as identity primary key,
    firstname   varchar(30) not null,
    surname     varchar(30) not null,
    patronymic  varchar(30) default null,
    position    varchar(50) not null, -- должность
    "managerID" int         references employees (id) on delete set null,
    "stationID" int references stations (id),
    "brigadeID" int references brigades (id),
    check ("stationID" is not null or "brigadeID" is not null)
);

create table if not exists "trainDeletionLog"
(
    id                   int generated by default as identity primary key,
    train_id             int         not null,
    train_number         varchar(20) not null,
    deleted_at           timestamp default now(),
    deleted_ticket_count int         not null
);
